#name: devops
#inputs:
#  myvar:
#    description: myvar
#    required: true
#runs:
#  using: composite
#  steps:
#    - name: set myvar
#      run: echo "myvar=${{ inputs.myvar }}" >> $GITHUB_ENV
#      shell: bash
#    - name: echo myvar
#      run: echo "myvar is $myvar"
#      shell: bash
#      
name: devops
inputs:
  myvar:
    description: myvar
    required: true
runs:
  using: composite
  steps:
    - name: set output
      id: id
      run: echo "::set-output name=myvar::${{inputs.myvar}}"
      shell: bash
    - name: echo myvar
      run: echo "${{ steps.id.outputs.myvar }}"
      shell: bash